# Generated by Django 5.2.12 on 2026-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_tag_remove_thread_icon_remove_thread_momentum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='thread_icons/'),
        ),
    ]
