# Generated by Django 5.2.12 on 2026-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_thread_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
