# Generated by Django 5.2.12 on 2026-03-21 17:00

import board.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_reply_image_reply_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=board.utils.upload_to_r2_thread),
        ),
    ]
