# Generated by Django 5.2.12 on 2026-03-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_thread_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
